CREATE TABLE SKIN_RESISTENCE(
  ID VARCHAR(20) PRIMARY KEY,
  TIME_OF_CREATION TIMESTAMP UNIQUE,
  VALUE INTEGER
);

CREATE TABLE MOOD(
  ID VARCHAR(20) PRIMARY KEY,
  TIME_OF_CREATION TIMESTAMP UNIQUE,
  MOOD VARCHAR(10)
);
